# Generated by Django 5.1.1 on 2024-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("zipcode", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("club", models.CharField(max_length=200)),
                ("club_email", models.EmailField(max_length=254)),
                ("club_phone", models.CharField(max_length=200)),
                ("club_address", models.CharField(max_length=200)),
                ("club_city", models.CharField(max_length=200)),
                ("club_state", models.CharField(max_length=200)),
                ("club_zipcode", models.CharField(max_length=200)),
            ],
        ),
    ]
